name: GitHub Actions Demo
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  MY_IP: ${{ steps.ip-address.outputs.ipv4 }}
run-name: Safetest
on:
  push:
    branches:
      - main
jobs:
  Safetest-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Public IP
        id: ip-address
        uses: haythem/public-ip@v1.3
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: npm install
        run: npm install
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Build
        run: npm run build
      - name: Build artifacts
        run: node build.js
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: 'Cache docker build for Safetest'
        run: node -e 'require("safetest/docker").buildDocker()'
      - name: 'Run Safetest tests'
        run: node test.js
      - run: echo "🍏 This job's status is ${{ job.status }}."
